name: libreconvert
description: "A powerful, offline-first file converter application built with Flutter for desktop platforms."
homepage: https://libretools.dev/libreconvert
repository: https://github.com/libre-tools/libreconvert

# This line prevents the package from being accidentally published to pub.dev.
publish_to: "none"

version: 1.0.2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.2.0
  dotted_border: ^3.0.1
  logger: ^2.6.0
  desktop_drop: ^0.6.0
  window_manager: ^0.5.0
  path_provider: ^2.1.5
  shadcn_flutter: ^0.0.37
  gap: ^3.0.1
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/logo.png"
  macos:
    generate: true
    image_path: "assets/logo.png"
  linux:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
