name: Build DEB

on:
  push:
    branches:
      - main

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Remove conflicting CMake (if any)
      run: |
        sudo rm -rf /usr/local/bin/cmake
        sudo rm -rf /usr/local/share/cmake-3.31
        which cmake || true
        cmake --version || true

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        path: ${{ runner.tool_cache }}/flutter
        key: ${{ runner.os }}-flutter-stable
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-cache-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-cache-

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Install DEB dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          dpkg-dev \
          fakeroot \
          libgtk-3-dev \
          pkg-config \
          desktop-file-utils

    - name: Build Linux release
      run: flutter build linux --release

    - name: Create .desktop file
      run: |
        echo "[Desktop Entry]" > libreconvert.desktop
        echo "Name=LibreConvert" >> libreconvert.desktop
        echo "GenericName=File Converter" >> libreconvert.desktop
        echo "Comment=A file conversion tool built with Flutter." >> libreconvert.desktop
        echo "Exec=/opt/libreconvert/libreconvert" >> libreconvert.desktop
        echo "Icon=libreconvert" >> libreconvert.desktop
        echo "Terminal=false" >> libreconvert.desktop
        echo "Type=Application" >> libreconvert.desktop
        echo "Categories=Utility;" >> libreconvert.desktop
        echo "StartupWMClass=dev.libretools.convert.libreconvert" >> libreconvert.desktop

    - name: Setup DEB package structure
      run: |
        mkdir -p deb_package/DEBIAN
        mkdir -p deb_package/opt/libreconvert
        mkdir -p deb_package/usr/bin
        mkdir -p deb_package/usr/share/applications
        mkdir -p deb_package/usr/share/icons/hicolor/scalable/apps

    - name: Create DEBIAN/control file
      run: |
        VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
        echo "Package: libreconvert" > deb_package/DEBIAN/control
        echo "Version: $VERSION" >> deb_package/DEBIAN/control
        echo "Section: x11" >> deb_package/DEBIAN/control
        echo "Priority: optional" >> deb_package/DEBIAN/control
        echo "Architecture: amd64" >> deb_package/DEBIAN/control
        echo "Maintainer: Raja <libretools@protonmail.com>" >> deb_package/DEBIAN/control
        echo "Depends: libgtk-3-0, libappindicator3-1, libjson-glib-1.0-0, libsecret-1-0, libglib2.0-0, libgdk-pixbuf2.0-0, libatk-bridge2.0-0, libsoup2.4-1, libwebkit2gtk-4.0-37" >> deb_package/DEBIAN/control
        echo "Description: A file conversion tool built with Flutter." >> deb_package/DEBIAN/control
        echo " This application allows you to convert various file formats." >> deb_package/DEBIAN/control

    - name: Copy application bundle
      run: cp -r build/linux/x64/release/bundle/* deb_package/opt/libreconvert/

    - name: Copy desktop and icon files
      run: |
        cp libreconvert.desktop deb_package/usr/share/applications/
        cp assets/logo.png deb_package/usr/share/icons/hicolor/scalable/apps/libreconvert.png
        chmod 755 deb_package/opt/libreconvert/libreconvert

    - name: Debugging: Check executable permissions and desktop file
      run: |
        echo "Permissions of deb_package/opt/libreconvert/libreconvert:"
        ls -l deb_package/opt/libreconvert/libreconvert
        echo "Content of libreconvert.desktop:"
        cat libreconvert.desktop
        echo "Contents of deb_package/opt/libreconvert:"
        ls -l deb_package/opt/libreconvert/

    - name: Build DEB package
      run: dpkg-deb --build deb_package

    - name: Extract version
      run: |
        VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Upload DEB artifact
      uses: actions/upload-artifact@v4
      with:
        name: libreconvert-deb-${{ env.VERSION }}-${{ github.sha }}
        path: deb_package.deb
