name: Build RPM

on:
  push:
    branches:
      - main

jobs:
  build-rpm:
    runs-on: fedora-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up DNF build dependencies
      run: |
        sudo dnf install -y \
          flutter \
          git \
          cmake \
          ninja-build \
          pkgconf-pkg-config \
          gtk3-devel \
          lzma-devel \
          lz4-devel \
          zstd-devel \
          desktop-file-utils \
          rpm-build \
          patchelf

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build Flutter Linux release
      run: flutter build linux --release

    - name: Create rpmbuild directory structure
      run: mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

    - name: Copy RPM spec file
      run: |
        if [ -f "libreconvert.spec" ]; then
          cp libreconvert.spec rpmbuild/SPECS/
        else
          echo "Error: libreconvert.spec not found in root directory"
          exit 1
        fi

    - name: Create source tarball
      run: |
        VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
        mkdir -p rpm_source/libreconvert-${VERSION}
        cp -r build/linux/x64/release/bundle/* rpm_source/libreconvert-${VERSION}/
        tar -czvf libreconvert-${VERSION}-bin.tar.gz -C rpm_source libreconvert-${VERSION}

    - name: Move tarball to SOURCES
      run: |
        VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
        mv libreconvert-${VERSION}-bin.tar.gz rpmbuild/SOURCES/

    - name: Build RPM
      run: rpmbuild -ba --define '_topdir ${{ github.workspace }}/rpmbuild' rpmbuild/SPECS/libreconvert.spec

    - name: Extract version
      run: |
        VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Upload RPM artifact
      uses: actions/upload-artifact@v4
      with:
        name: libreconvert-rpm-${{ env.VERSION }}-${{ github.sha }}
        path: rpmbuild/RPMS/x86_64/*.rpm
